---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: archlinux
    image: archlinux:latest
    # required to use custom Dockerfile.j2
    pre_build_image: false
    # required to actually load or check nft rules
    privileged: true
provisioner:
  name: ansible
verifier:
  name: ansible
