- name: Converge
  hosts: all
  vars:
    nft_debug: true
    nft_old_pkg_manage: false
    nft_service_manage: false
    nft_conf_dir_path: '/etc/nftables.d'
    nft_main_conf_path: '/etc/nftables.conf'
  tasks:
    - name: "Include nftables"
      ansible.builtin.include_role:
        name: "nftables"