---
- name: Converge
  hosts: all

  tasks:
    - name: "Include nftables"
      ansible.builtin.include_role:
        name: "nftables"
      vars:
        nft_debug: true
        nft_old_pkg_manage: false
        nft_service_manage: false
        # ensure config files land in the same places on Debian/RedHat for verify
        nft_conf_dir_path: '/etc/nftables.d'
        nft_main_conf_path: '/etc/nftables.conf'