---
name: ipr-cnrs.nftables.molecule

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  workflow_dispatch:

jobs:
  test:
    runs-on:  ubuntu-latest
    steps:

      - name: checkout
        uses: actions/checkout@v2
        with:
          path: "${{ github.repository }}"

      - name: Ansible Molecule
        uses: gofrolist/molecule-action@v2.3.2
        with:
          molecule_working_dir: "${{ github.repository }}"
