---
- name: Converge
  hosts: all
  tasks:
    - name: "Include nftables"
      ansible.builtin.include_role:
        name: "nftables"
  vars:
    nft_debug: true
    nft_old_pkg_manage: false
    nft_service_manage: false