---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: Gentoo
    image: gentoo/stage3:systemd
    privileged: true
    volumes:
      - /srv/gentoo-molecule/gentoo-repo:/var/db/repos/gentoo
      - /srv/gentoo-molecule/binpkgs:/var/cache/binpkgs
provisioner:
  name: ansible
verifier:
  name: ansible
